MoBike/MoBike/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion_usuario.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MoBike/gestion_usuario/urls.py
from django.conf.urls import url
from . import views
app_name = 'gestion_usuario'

urlpatterns = [
    url('home/', views.home, name='home'),
    url('registrar/', views.registrar, name='registrar'),
    url('login/', views.usuario_login, name='login'),
    url('logout/', views.usuario_logout, name='logout'),
    url('', views.index, name='index'),
]

MoBike/gestion_usuario/models.py
from django.db import models
from django.contrib.auth.models import User


class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='foto_perfil', blank=True)

MoBike/gestion_usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import PerfilUsuario


class   PerfilUsuarioForm(forms.ModelForm):
    class Meta():
        model = PerfilUsuario
        fields = ('foto_perfil',)
        # Labels nos cambia el texto del label que corresponde al input
        labels = {
            'foto_perfil': 'Foto de perfil'
        }


class RegistrarForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        labels = {
            'username': 'Nombre de usuario',
            'email': 'Correo',
            'password': 'Contraseña'
        }
        help_texts = {
            'username': '',
        }
        error_messages = {
            'username': {
                'max_length': 'Maximo 150 caracteres',
                'required': 'Requerido'
            },
            'password': {
                'required': 'Requerido'
            }
        }

    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

MoBike/gestion_usuario/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import RegistrarForm, PerfilUsuarioForm

## Cierre de sesion
def usuario_logout(request):
    logout(request)
    ##return HttpResponseRedirect(reverse('gestion_usuario:principal'))
    return render(request, 'gestion_usuario/index.html',{})

## renderizacion a pagina inicial
def index(request):
    return render(request, 'gestion_usuario/index.html',{})

## renderizacion a pagina inicial
def home(request):
    return render(request, 'home.html',{})

## Inicio de sesión    
def usuario_login(request):
    ##  Valida si existe un usuario autenticado
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse,('gestion_usuario:index'))
    else:
        # Recibe formulario mediante metodo POST
        if request.method == 'POST':
            ## Recibimos la informacion del formulario
            username = request.POST.get('username')
            password = request.POST.get('password')
            ## Autenticamos el usuario
            user = authenticate(username=username, password=password)
            ## Verifica que exista el usuario
            if user:
                ##Verifica si el usuario esta activo
                if user.is_active:
                    ## Genera un login para autenticar al usuario
                    login(request, user)
                    return HttpResponseRedirect(reverse('gestion_usuario:index'))
                else:
                    return HttpResponse("Tu cuenta esta inactiva.")
            else:
                ## Si no existe usuario
                print("username: {} - password: {}".format(username, password))
                return HttpResponse("Datos inválidos")
        else: ##Si llega desde una url en metodo GET (desde el navegador)
            return render(request, 'gestion_usuario/login.html', {})

## Registrar usuario nuevo
def registrar(request):
    registrado = False
    # Recibe formulario mediante metodo POST
    if request.method == 'POST':
        ## Crea formulario de usuario con informacion del request
        user_form = RegistrarForm(data=request.POST)
        ## Crea formulario de perfil con informacion del request
        profile_form = PerfilUsuarioForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            ## Guardamos en base de datos
            user = user_form.save()
            ## Encripta password con el modelo de django
            user.set_password(user.password)
            ## Guarda usuario tras encriptacion
            user.save()
            ## Instancia un objeto perfil
            profile = profile_form.save(commit=False)
            ## Asigna un usario al perfil
            profile.user = user
            ## Valida si en el Array FILES existe el archivo del input foto_perfil
            if 'foto_perfil' in request.FILES:
                ## Agrega la imagen al perfil
                profile.foto_perfil = request.FILES['foto_perfil']
            ## Guarda en base de datos
            profile.save()
            registrado = True
        else: ## Si alguno de los formularios es invalido
            print(user_form.errors, profile_form.errors)
            return HttpResponse("Datos inválidos")
    else: ## Si no es POST generamos los formularios
        user_form = RegistrarForm()
        profile_form = PerfilUsuarioForm()

    return render(request, 'gestion_usuario/registrar.html', 
                    {'user_form': user_form,
                     'profile_form': profile_form,
                     'registrado': registrado})

MoBike/gestion_usuario/templates/gestion_usuario/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
 
     <link rel="stylesheet" href="{% static 'css/index_design.css' %}">


    <title>Sucursal Usuario</title>
{% endblock head %}
{% block content %}
    <div class="contenedor-general">
      <h1>Bievenido/a a MoBike</h1>
      <p>¡Descárgate la App para empezar a pedalear hoy!</p>
      <!-- carrusel sacado de bootstrap hackers -->
      <div class="carrusel">
        <div
          id="carouselExampleIndicators"
          class="carousel slide"
          data-ride="carousel"
        >
          <ol class="carousel-indicators">
            <li
              data-target="#carouselExampleIndicators"
              data-slide-to="0"
              class="active"
            ></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <!-- la clase active dice que será la primera imagen en verse al ingresar a la página -->
            <div class="carousel-item active">
              <img
                src="{% static 'img/bici1.png'%}"
                class="d-block "
                alt="Bici1"
                style="margin: auto;"
              />
            </div>
            <div class="carousel-item">
              <img
                src="{% static 'img/bici2.png'%}"
                class="d-block "
                alt="Bici2"
                style="margin: auto;"
              />
            </div>

            <div class="carousel-item">
                <img
                  src="{% static 'img/gente1.png' %}"
                  class="d-block "
                  alt="Bici3"
                  style="margin: auto;"
                />
              </div>
                
          </div>
          <a
            class="carousel-control-prev"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Siguiente</span>
          </a>
        </div>
      </div>

      <div class="contenedor-acerca">
        <h1>Acerca de Mobike</h1>
        <p>
          Mobike es la más grande red de bicicletas compartidas. Con Mobike
          puedes moverte fácilmente por la ciudad sin necesidad de quedarte
          atascado en el tráfico, aparcar tu bicicleta en las estaciones más
          alejadas, ¡o incluso tener una bicicleta!
        </p>

        <p>
          Ya sea que vayas a trabajar o por diversión, Mobike está ahí para cada
          ocasión. Cuando lo necesites, busca una estación Mobike cerca de ti,
          desbloquea una bici y listo.
        </p>

        <p>
          ¡Usar MoBike es muy fácil! Así es como funciona:
        </p>

        <p>
          1. Abre la aplicación y encuentra la zona exclusiva Mobike más cercana
          en el mapa.
        </p>

        <p>
          2. Selecciona la zona exclusiva Mobike para encontrar cómo llegar a
          ella, o incluso reservar una bicicleta durante 15 minutos antes de
          utilizarla.
        </p>

        <p>
          3. Cuando encuentres tu Mobike, desbloquéala escaneando el código QR
          encima del candado de la rueda trasera, o el código QR en el medio del
          manillar.
        </p>
        <p>
          4. Una vez desbloqueada. ¡Disfruta de tu viaje sobre dos ruedas hasta
          tu zona exclusiva de destino!
        </p>
        <p>
          5. Una vez acabes tu viaje, indica tu RUT en el Tòtem MoBike, y
          estaciona la bicicleta en el bloque que se te indicará en pantalla.
        </p>
        <p>
          6. Bloquea la bicicleta deslizando el candado en la aplicación y obtén
          los detalles de tu viaje que aparecerán inmediatamente en tu
          aplicación.
        </p>
        <p>
          7. ¡Disfruta del resto del día sabiendo que has contribuido a mejorar
          tu ciudad y ahorrar dinero, al mismo tiempo!
        </p>
      </div>
      <!-- se usa id para linkearlo desde navbar -->
      <div id="contenedor-quienes-somos">
        <h1 class="titulo-quienes-somos">¿Quiénes somos?</h1>
        <div class="cont-imagenes-quienes-somos">
          <img src="{% static 'img/allan.png' %}" alt="Allan Collao" />
          <img src="{% static 'img/mujer.png' %}" alt="Constanza Díaz" />
          <img src="{% static 'img/pablo.png' %}" alt="Pablo Durán" />
        </div>
        <div class="cont-nombres-quienes-somos">
          <h3>Allan Collao</h3>
          <h3>Constanza Díaz</h3>
          <h3>Pablo Durán</h3>
        </div>

        <p>
          Somos un equipo de estudiantes de DuocUC. Cursamos la carrera de
          Analista programador computacional, en cuarto semestre. Hemos recibido
          el encargo de realizar una página web para el ramo de Desarrollo Web,
          por lo que optamos por desarrollar el proyecto MoBike.
        </p>
        <p></p>
      </div>
      <div class="contenedor-footer">
        <footer>
          <div class="googleplay">
            <a
              href="https://play.google.com/store/apps/details?id=com.mobike.mobikeapp&hl=es_CL"
              ><img src="{% static 'img/googleplay.png' %}" alt="Disponible en GooglePlay"
            /></a>
          </div>
          <div class="appstore">
            <a
              href="https://apps.apple.com/es/app/mobike-smart-bike-sharing/id1044535426"
              ><img src="{% static 'img/appstore.png' %}" alt="Disponible en AppStore"
            /></a>
          </div>
        </footer>
      </div>
    </div>

    
{% endblock content %}

MoBike/gestion_usuario/templates/gestion_usuario/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


    <title>Sucursal Usuario</title>
{% endblock head %}
{% block content %}

    <div class="login">
        <h1>Iniciar sesión</h1>
        <form method="post" class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Nombre Usuario:</label>
                <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
            </div>
            <div class="form-group">
                <label for="password">Contraseña:</label>
                <input type="password" class="form-control" name="password" placeholder="Contraseña">
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
    </div>

{% endblock content %}

MoBike/gestion_usuario/templates/gestion_usuario/registrar.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


    <title>Sucursal Usuario</title>
{% endblock head %}
{% block content %}
    <div class="jumbotron">
        {% if registrado %}
            <h1>¡Gracias por su registro!</h1>
        {% else %}
            <h1>Registro</h1>
            <h3>Completa los siguiente datos</h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p}}
                <button type="submit" class="btn btn-success">Registrar</button>
            </form>
        {% endif %}
    </div>
{% endblock content %}

MoBike/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.js'%}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/diseño_navbar.css' %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat"
    />

    {% block head %} 
    {% endblock %}
  </head>

  <body>
    <div class="container">
      <navbar class="barra-nav">
        <div class="logo">
          <img
            class="img-logo"
            src="{% static '/img/icono.png' %}"
            alt="LOGO_MOBIKE"
          />
        </div>
        <a class="btn">
          <span></span>
          <span></span>
          <span></span>
        </a>
        <div class="menu">
          <a href="{% url 'gestion_usuario:index' %}">Inicio</a>
          {% if not request.user.is_authenticated %}
          <a href="{% url 'gestion_usuario:login'%}">Iniciar sesión</a>
          <a href="{% url 'gestion_usuario:registrar' %}">Regístrate</a>
          {% else %}
          <a href="{% url 'gestion_usuario:logout' %}">Cerrar sesión</a>
          {% endif %}
        </div>
      </navbar>
    </div>
    <div class="container">
      {% block content %} 
      {% endblock %}
    </div>
  </body>
</html>